# Generated by Django 2.0.5 on 2018-05-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('Lome', 'Lome'), ('Kara', 'Kara')], max_length=50)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(upload_to='pictures')),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='covers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_projects', to='main.Author')),
            ],
        ),
    ]
